### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [VioletGiraffe/file-commander#157]
In file included from threading/cperiodicexecutionthread.cpp:1:0:
threading/cperiodicexecutionthread.h:11:102: error: ‘function’ in namespace ‘std’ does not name a template type
 iodicExecutionThread(unsigned int period_ms, const std::string& threadName, const std::function<void ()>& workload = std::function<void ()>());
                                                                                        ^~~~~~~~
threading/cperiodicexecutionthread.h:11:110: error: expected ‘,’ or ‘...’ before ‘<’ token
 cutionThread(unsigned int period_ms, const std::string& threadName, const std::function<void ()>& workload = std::function<void ()>());
                                                                                        ^
In file included from threading/cperiodicexecutionthread.cpp:1:0:
threading/cperiodicexecutionthread.h:18:30: error: ‘function’ in namespace ‘std’ does not name a template type
  void setWorkload(const std::function<void ()>& workload);
                              ^~~~~~~~
threading/cperiodicexecutionthread.h:18:38: error: expected ‘,’ or ‘...’ before ‘<’ token
  void setWorkload(const std::function<void ()>& workload);
                                      ^
threading/cperiodicexecutionthread.h:20:24: error: ‘function’ in namespace ‘std’ does not name a template type
  void start(const std::function<void ()>& workload = std::function<void ()>());
                        ^~~~~~~~
threading/cperiodicexecutionthread.h:20:32: error: expected ‘,’ or ‘...’ before ‘<’ token
  void start(const std::function<void ()>& workload = std::function<void ()>());
                                ^
threading/cperiodicexecutionthread.h:28:7: error: ‘function’ in namespace ‘std’ does not name a template type
  std::function<void ()> _workload;
       ^~~~~~~~
threading/cperiodicexecutionthread.cpp:14:1: error: prototype for ‘CPeriodicExecutionThread::CPeriodicExecutionThread(unsigned int, const string&, const std::function<void()>&)’ does not match any in class ‘CPeriodicExecutionThread’
 CPeriodicExecutionThread::CPeriodicExecutionThread(unsigned int period_ms, const std::string& threadName, const std::function<void()>& workload /*= std::function<void ()>()*/) :
 ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from threading/cperiodicexecutionthread.cpp:1:0:
threading/cperiodicexecutionthread.h:13:2: error: candidates are: CPeriodicExecutionThread::CPeriodicExecutionThread(const CPeriodicExecutionThread&)
  CPeriodicExecutionThread(const CPeriodicExecutionThread&) = delete;
  ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from threading/cperiodicexecutionthread.cpp:1:0:
threading/cperiodicexecutionthread.h:11:11: error:                 CPeriodicExecutionThread::CPeriodicExecutionThread(unsigned int, const string&, int)
  explicit CPeriodicExecutionThread(unsigned int period_ms, const std::string& threadName, const std::function<void ()>& workload = std::function<void ()>());
           ^~~~~~~~~~~~~~~~~~~~~~~~
threading/cperiodicexecutionthread.cpp:27:6: error: prototype for ‘void CPeriodicExecutionThread::setWorkload(const std::function<void()>&)’ does not match any in class ‘CPeriodicExecutionThread’
 void CPeriodicExecutionThread::setWorkload(const std::function<void()>& workload)
      ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from threading/cperiodicexecutionthread.cpp:1:0:
threading/cperiodicexecutionthread.h:18:7: error: candidate is: void CPeriodicExecutionThread::setWorkload(int)
  void setWorkload(const std::function<void ()>& workload);
       ^~~~~~~~~~~
threading/cperiodicexecutionthread.cpp:35:6: error: prototype for ‘void CPeriodicExecutionThread::start(const std::function<void()>&)’ does not match any in class ‘CPeriodicExecutionThread’
 void CPeriodicExecutionThread::start(const std::function<void()>& workload /*= std::function<void ()>()*/)
      ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from threading/cperiodicexecutionthread.cpp:1:0:
threading/cperiodicexecutionthread.h:20:7: error: candidate is: void CPeriodicExecutionThread::start(int)
  void start(const std::function<void ()>& workload = std::function<void ()>());
       ^~~~~
threading/cperiodicexecutionthread.cpp: In member function ‘void CPeriodicExecutionThread::threadFunc()’:
threading/cperiodicexecutionthread.cpp:60:7: error: ‘_workload’ was not declared in this scope
  if (!_workload)
       ^~~~~~~~~
threading/cperiodicexecutionthread.cpp:60:7: note: suggested alternative: ‘setWorkload’
  if (!_workload)
       ^~~~~~~~~
       setWorkload
threading/cperiodicexecutionthread.cpp:67:3: error: ‘_workload’ was not declared in this scope
   _workload();
   ^~~~~~~~~
threading/cperiodicexecutionthread.cpp:67:3: note: suggested alternative: ‘setWorkload’
   _workload();
   ^~~~~~~~~
   setWorkload
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-register’
cc1plus: warning: unrecognized command line option ‘-Wno-local-type-template-args’
cc1plus: warning: unrecognized command line option ‘-Wno-c++11-extensions’

**Comment by VioletGiraffe** [comment]
Which operating system? Which compiler?

Try adding `#include <functional>` to the top of cperiodicexecutionthread.h

**Comment by SolarAquarion** [comment]
Arch Linux.

gcc 7

**Comment by VioletGiraffe** [comment]
Have you tried adding `<functional>`?

**Comment by SolarAquarion** [comment]
Yes, but now i get this

src/shell/cshell.cpp:101:33: error: ‘item’ was not declared in this scope
  return QProcess::startDetached(item.fullAbsolutePath(), QStringList(), item.parentDirPath());
                                 ^~~~
src/shell/cshell.cpp:101:33: note: suggested alternative: ‘tm’
  return QProcess::startDetached(item.fullAbsolutePath(), QStringList(), item.parentDirPath());
                                 ^~~~
                                 tm
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-register’
cc1plus: warning: unrecognized command line option ‘-Wno-local-type-template-args’
cc1plus: warning: unrecognized command line option ‘-Wno-c++11-extensions’
make[1]: *** [Makefile:1315: ../build/release/core/cshell.o] Error 1
make[1]: Leaving directory '/home/solaraquarion/file-commander/file-commander-core'
make: *** [Makefile:134: sub-file-commander-core-make_first] Error 2

**Comment by VioletGiraffe** [comment]
Fixed. Update the repo with my latest changes, run `qmake` again and rebuild.
