### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [VioletGiraffe/file-commander#175]
src/panel/cpanelwidget.cpp: In member function ‘virtual void CPanelWidget::volumesChanged(const std::deque<VolumeInfo>&, Panel)’:
src/panel/cpanelwidget.cpp:740:28: error: ‘const struct VolumeInfo’ has no member named ‘displayName’
   QString name = driveInfo.displayName();

**Comment by SolarAquarion** [comment]
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -std=gnu++1y -Wall -Wno-c++11-extensions -Wno-local-type-template-args -Wno-deprecated-register -D_REENTRANT -fPIC -D_SCL_SECURE_NO_WARNINGS -DNDEBUG=1 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Isrc -I../file-commander-core/src -I../file-commander-core/include -I../qtutils -I../cpputils -I../github-releases-autoupdater/src -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtCore -I../build/release/x64/FileCommander -isystem /usr/include/libdrm -I../build/release/x64/FileCommander -I/usr/lib/qt/mkspecs/linux-g++ -o ../build/release/x64/FileCommander/cpanelwidget.o src/panel/cpanelwidget.cpp
src/panel/cpanelwidget.cpp: In member function ‘virtual void CPanelWidget::volumesChanged(const std::deque<VolumeInfo>&, Panel)’:
src/panel/cpanelwidget.cpp:740:28: error: ‘const struct VolumeInfo’ has no member named ‘displayName’
   QString name = driveInfo.displayName();
                            ^~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-register’
cc1plus: warning: unrecognized command line option ‘-Wno-local-type-template-args’
cc1plus: warning: unrecognized command line option ‘-Wno-c++11-extensions’
make[1]: *** [Makefile:1627: ../build/release/x64/FileCommander/cpanelwidget.o] Error 1
make[1]: Leaving directory '/home/solaraquarion/pkgbuild/file-commander-git/src/file-commander-git/qt-app'
make: *** [Makefile:58: sub-qt-app-make_first] Error 2
==> ERROR: A failure occurred in build().

**Comment by VioletGiraffe** [comment]
Fixed the compilation issue. But it's no use because the application crashes due to `QFileSystemWatcher` being constructed before `QApplication::exec()` call, which is apparently illegal (but used to work before). I've already had half a mind to throw `QFileSystemWatcher` away because it fails to detect some changes. I'm assigning #12 top priority and will get to it as soon as possible.

I'll look into the `#pragma` warnings, too, but that's not critical.

**Comment by SolarAquarion** [comment]
@VioletGiraffe I'm now getting a fragmentation fault

**Comment by VioletGiraffe** [comment]
Yep. As I said, it crashes on Mac and Linux. I'm working on it right now.

**Comment by VioletGiraffe** [comment]
Fixed.
