### ISSUE TITLE
Please provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [VioletGiraffe/file-commander#187]
file-commander is already using `linuxdeployqt` on Travis CI, a combination that could easily be used to produce an [AppImage](http://appimage.org/).

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

Please see https://github.com/probonopd/linuxdeployqt/#using-linuxdeployqt-with-travis-ci for an example on how to use `linuxdeployqt` on Travis CI to build an AppImage. If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by VioletGiraffe** [comment]
Work in progress: I immediately decided to provide a download once I've learned about the AppImage format, but I want to have a reasonably stable and working version of the program first.

**Comment by VioletGiraffe** [comment]
Closing for now as linuxdeployqt is too early in development to be used for real projects (https://github.com/probonopd/linuxdeployqt/issues/237, https://github.com/probonopd/linuxdeployqt/issues/357).

**Comment by probonopd** [comment]
Can you point me to the build script, build log, and AppImage for test?

**Comment by probonopd** [comment]
> linuxdeployqt is too early in development to be used for real projects

Hundreds of projects have been using it, so we can certainly make it work for your project as well. Please point me to the build script, build log, and AppImage for test.

**Comment by probonopd** [comment]
Is there an AppImage download available now or will there ever? Thanks for considering making one available.

**Comment by VioletGiraffe** [comment]
@probonopd, I'd love to provide one even just for my personal use because it would be very convenient, but I have not been able to figure out how to bundle additional .so libraries properly that are loaded at runtime (that is, not directly referenced to by the main application).

**Comment by probonopd** [comment]
In case you are using [linuxdeployqt](https://github.com/probonopd/linuxdeployqt/):

1. Copy the additional libraries into the AppDir
2. Supply them to `-executable=<path>` when you call `linuxdeployqt` (you can have multiple `-executable=<path>`

Please ping me with a build log file in case you are running into issues. Happy to help.

**Comment by VioletGiraffe** [comment]
@probonopd, thank you, I appreciate it and I'm working on it right now. One oddity I just encountered:
```ERROR: "~/Qt/5.15.0/gcc_64/bin/qmake -query" exited with 255 : ""
ERROR: Qt path could not be determined from qmake on the $PATH
ERROR: Make sure you have the correct Qt on your $PATH```

Indeed, qmake is not on my path, I thought that's the whole point of specifying the option `-qmake=<qmake path>`?

**Comment by probonopd** [comment]
Hum, interesting. Would it hurt to `export PATH=...` before you invoke `linuxdeployqt`?

**Comment by VioletGiraffe** [comment]
Sorry for rushing to ping you before thinking. I realized it just failed to invoke qmake from the path I specified, so I replaced `~` with full home path and it worked. Would be more intuitive if `~` was supported, though.
And no, I don't think it would hurt, I was just puzzled by an option that targets specifically this task and then fails to work (seemingly).

**Comment by VioletGiraffe** [comment]
I've successfully ended up with an AppImage file, but I get this when trying to run it. How do I troubleshoot this?
`execv error: No such file or directory`

**Comment by probonopd** [comment]
Can you post the AppImage so that I can inspect it?

**Comment by VioletGiraffe** [comment]
@probonopd, here you go: https://mega.nz/file/8rZgUa4a#I4s-ZkqJGDvZKYOu7UVP6_aQ80M3OVPZM9799IZ9iF4

**Comment by probonopd** [comment]
```
# Extract the AppImage
me@host:~$ '/home/me/Downloads/File_Commander-f73f7c0-x86_64.AppImage' --appimage-extract

# Inspect its AppRun file
me@host:~$ ls squashfs-root/AppRun 
squashfs-root/AppRun

# Notice that it's a broken symlink
me@host:~$ ls -lh squashfs-root/AppRun 
lrwxrwxrwx 1 me me 30 Jul 31 23:13 squashfs-root/AppRun -> installation/bin/FileCommander

# Fix that issue
me@host:~$ ( cd squashfs-root/ ; rm AppRun ; ln -s FileCommander AppRun )

# See if it runs now
me@host:~$ squashfs-root/AppRun 
Segmentation fault
```

Now, that's another issue... which brings me to the question: How exactly did you invoke `linuxdeployqt` so that `lib/libstdc++.so.6` ended up in there!?

**Comment by VioletGiraffe** [comment]
Hm. I did not create that AppRun, it was there, but maybe it had been there for a long since my old experiments with linuxdeployqt. I'll nuke the directory to remove any junk and will try again.
As for you question: I used `-unsupported-bundle-everything -unsupported-allow-new-glibc` as I'm building on Ubuntu 20.04.

**Comment by probonopd** [comment]
Please do not use any of the `-unsupported` flags as they are known not to work (at least not without additional manual work). Can you build on Ubuntu xenial?

**Comment by VioletGiraffe** [comment]
> Can you build on Ubuntu xenial?
Only using some kind of CI (Travis, Github actions), but that is more difficult to debug, I wanted to get a working package locally first. I'll start by removing the `bundle-everything` flag to see if the resulting package runs locally.

**Comment by probonopd** [comment]
...or just run a xenial Live ISO locally
