### ISSUE TITLE
FreeBSD: program freeze on startup

### ISSUE THREAD

**Issue by treehugging-green-wolf** [VioletGiraffe/file-commander#236]
under FreeBSD, when I launch FileCommander, the program freezes and does not load until I do one of the following:

- press alt/shift/ctrl/win keys
- press one of the destop environment shortrcut keys
- click anywhere with the mouse

after some debugging, I found that the program  gets to `app.exec()` in `main()`, and freezes.

putting a breakpoint in `NativeEventFilter::nativeEventFilter` yielded this function is not reached.

then,reading the sources revealed that `CMainWindow::show()` is called only from whithin `NativeEventFilter::nativeEventFilter,`
which means the main window will not load until some other  events are received.

adding `w.show();`  to `main()` fixed the issue.

maybe it would be better to initialize the main window from `main()`?

**Comment by VioletGiraffe** [comment]
That piece of code is pretty weird, I don't remember why I implemented it in such a convoluted way. Usually `QMainWindow::show()` is called from `main()` just like you suggest. 
On the other hand, I don't understand why it halgs. Is there no `show event` on FreeBSD? I have a hard time believing the application literally doesn't receive a single event until the window is shown or until you generate an event artificially.

**Comment by VioletGiraffe** [comment]
If it requires asynchronous (delayed) initialization, then a much cleaner way would be `QTimer::singleShot` inside `main()`, but the fact is I don't know why the current code is so complicated and I'm not keen on touching it. But I'll experiment with it and see what breaks, can you do the same on your OS?

This is what happens when programmers don't write comments :)

**Comment by treehugging-green-wolf** [comment]
you mean experiment with `QTimer::singleShot` ?

**Comment by VioletGiraffe** [comment]
Maybe that, maybe just plain 
```
w.onCreate();
w.updateInterface();
```
in `main()`. I did a quick try, deleted the `NativeEventFilter`, don't see any problems.

**Comment by VioletGiraffe** [comment]
I've just commited this change for easier testing.

**Comment by treehugging-green-wolf** [comment]
#### my tests  resulted as follows:
#### with `w.onCreate();`: program prints 

> Built with Qt 5.12.2
> Running with Qt 5.12.2
> "Loaded plugin \"File comparison plugin\" (libplugin_filecomparison.so.1.0.0)"
> "Loaded plugin \"Image viewer plugin\" (libplugin_imageviewer.so.1.0.0)"
> "Loaded plugin \"Plain text and HTML viewer plugin\" (libplugin_textviewer.so.1.0.0)"

// and freezes
then I generate an event, and the program prints :

> Assertion failed at CController, line 26: _instance == nullptr
> "Loaded plugin \"File comparison plugin\" (libplugin_filecomparison.so.1.0.0)"
> "Loaded plugin \"Image viewer plugin\" (libplugin_imageviewer.so.1.0.0)"
> "Loaded plugin \"Plain text and HTML viewer plugin\" (libplugin_textviewer.so.1.0.0)"
> Assertion failed at setPanelPosition, line 132: _panelPosition == UnknownPanel
> Assertion failed at setPanelPosition, line 57: _panelPosition == UnknownPanel
> Assertion failed at setPanelPosition, line 132: _panelPosition == UnknownPanel
> Assertion failed at setPanelPosition, line 57: _panelPosition == UnknownPanel

#### with `w.updateInterface()`: program prints 

> Built with Qt 5.12.2
> Running with Qt 5.12.2
> "Loaded plugin \"File comparison plugin\" (libplugin_filecomparison.so.1.0.0)"
> "Loaded plugin \"Image viewer plugin\" (libplugin_imageviewer.so.1.0.0)"
> "Loaded plugin \"Plain text and HTML viewer plugin\" (libplugin_textviewer.so.1.0.0)"

and loads fine

**Comment by VioletGiraffe** [comment]
I get a feeling you were trying either `onCreate` or `updateInterface`, but they need to be used together. I committed the appropriate change earlier, can you give it a try? It works fine for me on Windows. Unfortunately, I need to have Microsoft Hyper-V enabled and VMWare Player is incompatible with it, so I can no longer test on my VMWare Linux system. I'll see what I can get going in Oracle Virtualbox.

**Comment by treehugging-green-wolf** [comment]
Just tested the latest version from master and it works fine under freebsd.
