### ISSUE TITLE
Thank you very much for the free open source program!

### ISSUE THREAD

**Issue by mrkaban** [VioletGiraffe/file-commander#267]
Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%83%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D1%8B/%D1%84%D0%B0%D0%B9%D0%BB%D1%8B-%D0%B8-%D0%BF%D0%B0%D0%BF%D0%BA%D0%B8/file-commander-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D1%8B%D0%B9-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80.html).

The project is interesting, so please don't abandon it!

**Comment by VioletGiraffe** [comment]
Thank you! It's far from abandoned and I have many improvements planned, just not much time lately to dedicate to it. And even more importantly, I use this file manager every day, all the time, on all of my computers, and I've implemented most of the things I need. Obviously, other users may need other things or may discover new bugs in their unique workflows, I'm just not as motivated to implement or fix things that don't affect myself.
