### ISSUE TITLE
Mouse Extra-Button Support

### ISSUE THREAD

**Issue by Velho** [VioletGiraffe/file-commander#284]
As the basic File Explorers provided by Gnome, Kde, Exploer, etc usually provided support for Mouse Button interaction.

Extra buttons usually assigned to backward and forward then reflecting this in the software.
Instead of using those extra buttons as replacements for left clicks it would be nice to use them to navigate the file structure or assign some other features to them per user needs.

**Comment by Velho** [comment]
Now I am just mistakenly moving folders around, gladly it confirms if I want to perform the action.

**Comment by VioletGiraffe** [comment]
What's the model of your mouse, what kinds of extra buttons does it have? My Logitech has 5 extra buttons, but they are fully configurable in the Logitech software. Other software can only detect them as the configured action, it's not possible to detect e. g. "extra mouse button # 3 down".

**Comment by Velho** [comment]
Logitech Pro Wireless

**Comment by VioletGiraffe** [comment]
I don't have this mouse so I won't be able to do anything. Maybe you can use the Logitech software to create an application-specific control profile for File Commander and reassign buttons as you like. Or you can build the program from source, use the debugger, and see which key press events correspond to different buttons. Then you can remap these events.

See `CFileListView` and its `mousePressEvent` and `keyPressEvent`.
