### ISSUE TITLE
Please do support MSIX.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [VioletGiraffe/file-commander#288]

**Comment by VioletGiraffe** [comment]
That certainly would not provide any benefits over the existing InnoSetup installer. What is the motivation behind this request?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This comment is response to “https://github.com/VioletGiraffe/file-commander/issues/288#issuecomment-1002717712”.

Although numerous benefits are present, the most important is that winget and basic package-managers that are similar to winget shall be able to properly manage the package. This is partially true for MSI, but MSIX is an open standard, and correct support of it is superior.

**Comment by VioletGiraffe** [comment]
I hate MSI for its slow operation and especially for littering: it leaves a copy of the MSI package in the "Installers" directory for as long as the application is installed, which is just wasted space. Does MSIX do anything similar?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This comment is response to “https://github.com/VioletGiraffe/file-commander/issues/288#issuecomment-1002796301”.

You are able to test this easily, because within “file:///%systemdrive%/ProgramFiles/” is all of the information that is being stored for software that has been installed by APPX and MSIX installers.

After gaining access to the directory, compare it before and after installation of some software via one MSIX package. My knowledge of this process is that it should not leave any data. Anecdotal demonstration of this is how uninstallation and subsequent installation of Minecraft: Bedrock Edition during some years before now did not retain the data that had been created by it.

**Comment by VioletGiraffe** [comment]
Thank you for the answer. I still think InnoSetup is superior to MSIX, I'm not interested in learning MSIX. But you can convince me otherwise by explaining why exactly you don't like the current setup package and why you suggest MSIX specifically of all the different available choices.
