### ISSUE TITLE
Keybindings

### ISSUE THREAD

**Issue by frostmorn** [VioletGiraffe/file-commander#294]
Keybinding for hide or show hidden files can't work, cause same binding used to open Help in menu.

**Comment by VioletGiraffe** [comment]
Well that's embarassing, will fix it (by changing from Alt + H to something else, probably Alt + Shift + H, or maybe Ctrl + H).

**Comment by frostmorn** [comment]
Some managers have something like Alt + .  
dot have a strong sense for unix systems, cause that's a way to make file being hidden, filename simply starts from it

**Comment by ftphikari** [comment]
Why was this issue closed? No commit seemed to have fixed this. Ctrl+H is the default keybinding I have seen on all Linux file managers, so that's what I expect.

**Comment by frostmorn** [comment]
@ftphikari it's closed due to my missclick action :D
whatever, thought it's not a very hard problem to solve, so supposed that it was allready fixed and there're no reasons to talk about it.

**Comment by VioletGiraffe** [comment]
Not hard at all, but I forgot about, so thanks for pointing it out :)
