### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by SolarAquarion** [VioletGiraffe/file-commander#307]
g++ -c -pipe -pedantic-errors -march=x86-64 -mtune=generic -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/file-commander-git/src=/usr/src/debug/file-commander-git -flto=auto -O3 -fPIC -std=c++2a -flto -fno-fat-lto-objects -Wall -D_REENTRANT -DNDEBUG=1 -DPLUGIN_MODULE -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -Isrc -Iinclude -I../qtutils -I../cpputils -I../cpp-template-utils -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I../build/release/x64/core -I/usr/lib/qt/mkspecs/linux-g++ -o ../build/release/x64/core/cvolumeenumerator_impl_linux.o src/diskenumerator/cvolumeenumerator_impl_linux.cpp
src/diskenumerator/cvolumeenumerator_impl_linux.cpp:4:31: error: no declaration matches ‘const std::vector<VolumeInfo> CVolumeEnumerator::enumerateVolumesImpl()’
    4 | const std::vector<VolumeInfo> CVolumeEnumerator::enumerateVolumesImpl()
      |                               ^~~~~~~~~~~~~~~~~
In file included from src/diskenumerator/cvolumeenumerator_impl_linux.cpp:1:
src/diskenumerator/cvolumeenumerator.h:49:54: note: candidate is: ‘static std::vector<VolumeInfo> CVolumeEnumerator::enumerateVolumesImpl()’
   49 |         [[nodiscard]] static std::vector<VolumeInfo> enumerateVolumesImpl();
      |                                                      ^~~~~~~~~~~~~~~~~~~~
src/diskenumerator/cvolumeenumerator.h:16:7: note: ‘class CVolumeEnumerator’ defined here
   16 | class CVolumeEnumerator final : public QObject
      |       ^~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:784: ../build/release/x64/core/cvolumeenumerator_impl_linux.o] Error 1
make[1]: Leaving directory '/build/file-commander-git/src/file-commander/file-commander-core'
make: *** [Makefile:139: sub-file-commander-core-make_first] Error 2

**Comment by VioletGiraffe** [comment]
I see that the automated builds are also broken, thanks for pointing it out. I'll fix it the first thing tomorrow.

**Comment by VioletGiraffe** [comment]
In the meantime, you can just check out an older revision, for example, the latest release.

**Comment by VioletGiraffe** [comment]
Fixed.
