### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by Ygarr** [VioletGiraffe/file-commander#326]
Qt6 installed.
libxcb installed.
Arch-based.
./FileCommander.appimage 
Built with Qt 6.6.1
Running with Qt 6.6.1
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

fish: Job 1, './FileCommander.appimage' terminated by signal SIGABRT (Abort)

**Comment by VioletGiraffe** [comment]
I have only seen that in gui-less environments (e. g. with a monitor unplugged - when the system has a desktop environment, but no active display is present).

**Comment by VioletGiraffe** [comment]
You can see more detailed error messages with `export QT_DEBUG_PLUGINS=1`

There are also different Qt backends to try, e. g. `export QT_QPA_PLATFORM=minimal`, but I can't find a full list. For Wayland there's `export QT_QPA_PLATFORM=wayland` etc.
