### ISSUE TITLE
OS X: Ctrl+Q "Quick view" shortcut becomes Cmd+Q and conflicts with the system "Quit" command

### ISSUE THREAD

**Issue by VioletGiraffe** [VioletGiraffe/file-commander#75]

**Comment by antis81** [comment]
:+1: Actually it's exactly reversed (`Cmd+Q` is for quit on OSX). You'd have to teach Qt to use explicitly `Ctrl+Q` (-> Qt::Key_Meta + Qt::Key_Q). By default, Qt replaces a `Ctrl+Q` with `Meta+Q` on OSX.

I suggest to change the "QuickView" shortcut to `Ctrl+Shift+Q`, which works for all platforms. Further add a quit action to the file menu for Linux and Windows. On Linux, Ctrl+Q is a convience for "Quit" on most modern applications (Firefox, Thunderbird, LibreOffice, QtCreator, and many more ...).

For reference, have a look at `Qt::AA_MacDontSwapCtrlAndMeta` and `Qt::Key_Meta` / `Qt::Key_Control` in Qt's documentation.

Another option for Linux and Windows is, using `Space` as a shortcut. On OSX this usually opens "QuickLook".

**Comment by VioletGiraffe** [comment]
Thanks for the tips! Guess I'll fix this today. I didn't know all that. Guess now I can fix this issue today!
