### ISSUE TITLE
QtCreator warnings

### ISSUE THREAD

**Issue by AcarBurak** [VioletGiraffe/file-commander#87]
In Linux (Arch Linux with Fluxbox window manager) QtCreator produces these messages:

Could not find .pro file for subdirectory "qtutils" in "/home/burak/bin/file-commander/qtutils".
Could not find .pro file for subdirectory "text_encoding_detector" in "/home/burak/bin/file-commander/text-encoding-detector/text-encoding-detector".
Could not find .pro file for subdirectory "cpputils" in "/home/burak/bin/file-commander/cpputils".
Warnings while parsing QML type information of /usr/lib/qt/qml:
<dump of /usr/lib/qt/qml>:1:24: Reading only version 1.1 parts.
<dump of /usr/lib/qt/qml>:10:5: Expected only Component and ModuleApi object definitions.

**Comment by VioletGiraffe** [comment]
That's because you didn't run the `update_repository` script. Run it and reload the project.

**Comment by AcarBurak** [comment]
All right, thanks, but still:

Warnings while parsing QML type information of /usr/lib/qt/qml:
<dump of /usr/lib/qt/qml>:1:24: Reading only version 1.1 parts.
<dump of /usr/lib/qt/qml>:10:5: Expected only Component and ModuleApi object definitions.

**Comment by VioletGiraffe** [comment]
Since there's no QML in the project whatsoever, I'd say that's a Qt Creator bug.

**Comment by AcarBurak** [comment]
Anyway, command line has worked.
